### ISSUE TITLE
directory to store data_set

### ISSUE THREAD

**Issue by qzhu2017** [yanxon/RDF#1]
@yanxon 
In order to let people can quickly reproduce your results.

I suggest you create a directory called source_data, in which you download and dump these data in json format.
For instance, 
`sp_metal_aflow_844.json`
For each structure, you save the following information,
- structure - lattice, coord, atom array
- property - dos, band-gap, formation energy, .etc.

**Comment by yanxon** [comment]
@qzhu2017 

What do you mean by atom array?

For example in this POSCAR file:
Al2Dy1   [FCC,FCC,cF24] (STD_PRIM doi:10
   1.22474500000000     
     0.0000000000000000    3.2132347243975312    3.2132347243975312
     3.2132347243975312    0.0000000000000000    3.2132347243975312
     3.2132347243975312    3.2132347243975312    0.0000000000000000
   4   2
Direct
  0.6250000000000000  0.6250000000000000  0.6250000000000000
  0.6250000000000000  0.6250000000000000  0.1250000000000000
  0.6250000000000000  0.1250000000000000  0.6250000000000000
  0.1250000000000000  0.6250000000000000  0.6250000000000000
  0.0000000000000000 -0.0000000000000000  0.0000000000000000
  0.2500000000000000  0.2500000000000000  0.2500000000000000
 
  0.00000000E+00  0.00000000E+00  0.00000000E+00
  0.00000000E+00  0.00000000E+00  0.00000000E+00
  0.00000000E+00  0.00000000E+00  0.00000000E+00
  0.00000000E+00  0.00000000E+00  0.00000000E+00
  0.00000000E+00  0.00000000E+00  0.00000000E+00
  0.00000000E+00  0.00000000E+00  0.00000000E+00

line#3-5 are the lattice (a,b,c,alpha,beta,gamma)
line#8-13 are the atomic positions (Is this what you meant by coord?)

Thanks,

Howard

**Comment by qzhu2017** [comment]
@yanxon 

check this code:
https://github.com/qzhu2017/ML-DOS/blob/master/json_example.py

**Comment by yanxon** [comment]
@qzhu2017 

Thank you. For AFLOW, when you call this command: entry.geometry, it will return the angles 60 deg for cubic system. Do you have any idea?

**Comment by qzhu2017** [comment]
@yanxon 
In crystallography, there are different types of crystals. If you look at the space group symbols, they start with P, A, C, I, F. 
- P stands for primitive unit cell, 
- A, C, I stand for the cell which are A, C, or body centered conventional unit cell. 
- F stands for face centered unit cell. Like what we call fcc.
For non centered conventional unit cell, you can always convert it to a cell containing smallest number of atoms. This is good for simulation, because we don't need to computation many atoms.
When FCC is converted to the primitive cell, you got the angle of 60 degrees.
